# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: Prasdevops

steps:

- bash: |
    echo $(date +%Y)
    echo '##vso[task.setvariable variable=buildName]$(date +%Y)_$(date +%m)_$(Build.BuildNumber)_v3.7'

- bash: |
    echo $(buildName)
    
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'  # or 'Cobertura', depending on your tool
    summaryFileLocation: 'target/site/jacoco/jacoco-s.exec'  # Adjust the path as necessary
    reportDirectory: 'target/site/jacoco'  # Adjust to where the report is generated
    failIfCoverageEmpty: false  # Optional: fail the build if no coverage is found